name: flatlandsio_env
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- setuptools=36.4.0=py36_1
- wheel=0.29.0=py36_0
- pip:
  - click==6.7
  - flask==0.12.2
  - flask-sqlalchemy==2.3.2
  - gunicorn==19.7.1
  - itsdangerous==0.24
  - jinja2==2.9.6
  - markdown==2.6.9
  - markupsafe==1.0
  - sqlalchemy==1.1.15
  - werkzeug==0.12.2